runtime: python27
api_version: 1
threadsafe: yes
service: service1


handlers:

- url: /admin/notadmin
  static_files: templates/NotAdmin.html
  upload: templates/NotAdmin.html
- url: /admin/.*
  script: Admin.app

- url: /css
  static_dir: templates/css
- url: /js
  static_dir: templates/js


- url: /.*
  script: Main.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

