runtime: python27
api_version: 1
threadsafe: yes
service: service1


handlers:

- url: /manage/.*
  script: Main.app
  login: required
  auth_fail_action: redirect


- url: /.*
  script: Main.app




libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

