runtime: python27
api_version: 1
threadsafe: yes
service: default

handlers:

- url: /admindash/.*
  script: google.appengine.ext.admin.application
- url: /admin/notadmin
  static_files: templates/admin/NotAdmin.html
  upload: templates/admin/NotAdmin.html
- url: /admin/.*
  script: source.Admin.app


# [START views]
- url: /viewstream
  script: source.views.ViewStream.app
- url: /search
  script: source.views.TextSearch.app
# [START views]


# [START services]
- url: /services/viewstream
  script: source.services.Service_ViewStream.app
- url: /services/insertteststream
  script: source.services.InsertTestStream.app
- url: /services/upload.*
  script: source.services.Service_UploadFile.app
- url: /services/management
  script: source.services.Service_Management.app
- url: /services/deletestream
  script: source.services.Service_DeleteStream.app
- url: /services/subscribe
  script: source.services.Service_Subscribe.app
- url: /services/unsubscribe
  script: source.services.Service_Subscribe.app
- url: /services/crontrends*
  script: source.services.Service_CronTrends.app
- url: /services/search
  script: source.services.Service_TextSearch.app
# [END services]

- url: /css
  static_dir: templates/css
- url: /js
  static_dir: templates/js


- url: /.*
  script: source.Main.app


# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
