runtime: python27
api_version: 1
threadsafe: yes
service: default

handlers:

- url: /admindash/.*
  script: google.appengine.ext.admin.application
- url: /admin/notadmin
  static_files: templates/admin/NotAdmin.html
  upload: templates/admin/NotAdmin.html
- url: /admin/.*
  script: source.Admin.app


# [START views]
- url: /search.*
  script: Routes.app
- url: /viewall
  script: Routes.app
- url: /viewstream
  script: Routes.app
- url: /viewtag
  script: Routes.app
- url: /create
  script: Routes.app
- url: /delete.*
  script: Routes.app
- url: /unsubscribe.*
  script: Routes.app
- url: /error
  script: Routes.app
- url: /manage
  script: Routes.app
- url: /tagmod
  script: Routes.app
- url: /social
  script: Routes.app
# [START views]


# [START services]
- url: /services/insertteststream
  script: source.services.InsertTestStream.app
- url: /services/crontrends*
  script: source.services.Service_CronTrends.app
- url: /services/management
  script: Routes.app
- url: /services/search.*
  script: Routes.app
- url: /services/viewstream
  script: Routes.app
- url: /services/upload.*
  script: Routes.app
- url: /services/deletestream
  script: Routes.app
- url: /services/subscribe
  script: Routes.app
- url: /services/unsubscribe
  script: Routes.app
- url: /services/createtag
  script: Routes.app
- url: /services/createstream
  script: Routes.app
- url: /services/subscribed
  script: Routes.app
- url: /services/addstreamtag
  script: Routes.app
- url: /services/removestreamtag
  script: Routes.app
- url: /services/taggedstreams
  script: Routes.app
- url: /services/autocomplete
  script: Routes.app
# [END services]

- url: /css
  static_dir: templates/css
- url: /js
  static_dir: templates/js
- url: /images
  static_dir: templates/images


- url: /.*
  script: source.Main.app


# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
