runtime: python27
api_version: 1
threadsafe: yes
service: default

handlers:

- url: /admindash/.*
  script: google.appengine.ext.admin.application

- url: /viewstream
  script: ViewStream.app

- url: /admin/notadmin
  static_files: templates/admin/NotAdmin.html
  upload: templates/admin/NotAdmin.html
- url: /admin/.*
  script: Admin.app

# [START services]
- url: /services/viewstream
  script: ViewStreamService.app
- url: /services/insertteststream
  script: InsertTestStream.app
- url: /services/upload.*
  script: UploadFileService.app
# [END services]

- url: /css
  static_dir: templates/css
- url: /js
  static_dir: templates/js


- url: /.*
  script: Main.app


# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]